// 种子数据：染整离线作业台初始状态
import type { WorkbenchState } from "./types";

const now = Date.now();
const day = 86400000;

export function buildSeedState(): WorkbenchState {
  return {
    technician: "陈技术员",
    network: "online",
    migrated: false,
    replayedCurveNumbers: [],
    recipes: [
      {
        id: "r1",
        name: "棉府绸活性红配方",
        version: 1,
        motherLiquorRatio: 0.05,
        dyes: [
          { name: "活性红 3BF", concentration: 2.4 },
          { name: "活性黄 3RS", concentration: 0.6 },
        ],
        updatedAt: now - 10 * day,
      },
      {
        id: "r2",
        name: "涤纶分散蓝配方",
        version: 1,
        motherLiquorRatio: 0.04,
        dyes: [
          { name: "分散蓝 2BLN", concentration: 3.0 },
          { name: "分散红玉", concentration: 0.8 },
        ],
        updatedAt: now - 8 * day,
      },
    ],
    finishings: [
      { id: "f1", name: "柔软整理", version: 1, softener: 2.0, updatedAt: now - 6 * day },
      { id: "f2", name: "防水整理", version: 1, softener: 0, updatedAt: now - 5 * day },
    ],
    repairReasons: [
      { id: "rr1", label: "首次染色", version: 1, updatedAt: now - 4 * day },
      { id: "rr2", label: "色花复修", version: 1, updatedAt: now - 3 * day },
    ],
    motherLiquors: [
      { id: "ml1", code: "ML-2601", name: "活性红母液", stockL: 18, batchNo: "ML2601A" },
      { id: "ml2", code: "ML-2602", name: "分散蓝母液", stockL: 6, batchNo: "ML2602B" },
      { id: "ml3", code: "ML-2603", name: "活性黄母液", stockL: 25, batchNo: "ML2603C" },
    ],
    slots: [
      { id: "s1", code: "染缸A", capacityL: 300, bookings: [] },
      { id: "s2", code: "染缸B", capacityL: 200, bookings: [] },
      { id: "s3", code: "染缸C", capacityL: 150, bookings: [] },
    ],
    orders: [
      {
        id: "o1",
        code: "PO-2609",
        customer: "优衣库供应商",
        batchIds: ["b1"],
        signed: true,
        signedAt: now - 2 * day,
      },
      {
        id: "o2",
        code: "PO-2610",
        customer: "内销品牌",
        batchIds: ["b2"],
        signed: false,
      },
    ],
    batches: [
      {
        id: "b1",
        code: "LAB-620A",
        orderId: "o1",
        technician: "陈技术员",
        fabric: "棉府绸 120g",
        weightKg: 12,
        bathRatio: 10,
        recipeId: "r1",
        recipeVersion: 1,
        finishingId: "f1",
        finishingVersion: 1,
        repairId: "rr1",
        repairVersion: 1,
        motherLiquorId: "ml1",
        slotId: "s1",
        status: "已完成",
        conflicts: [],
        createdAt: now - 2 * day,
        startedAt: now - 2 * day,
      },
      {
        id: "b2",
        code: "LAB-621C",
        orderId: "o2",
        technician: "李技术员",
        fabric: "涤纶针织",
        weightKg: 20,
        bathRatio: 8,
        recipeId: "r2",
        recipeVersion: 1,
        finishingId: "f2",
        finishingVersion: 1,
        repairId: "rr2",
        repairVersion: 1,
        motherLiquorId: "ml2",
        slotId: "s2",
        status: "待排",
        conflicts: [],
        createdAt: now - 1 * day,
      },
      {
        // 旧批次：缺母液编号，迁移时需升级（合法，可升级）
        id: "b3",
        code: "LAB-624B",
        technician: "陈技术员",
        fabric: "混纺斜纹",
        weightKg: 15,
        bathRatio: 10,
        recipeId: "r1",
        recipeVersion: 1,
        finishingId: "f1",
        finishingVersion: 1,
        repairId: "rr1",
        repairVersion: 1,
        status: "待排",
        conflicts: [],
        createdAt: now - 12 * day,
      },
      {
        // 损坏旧批次：缺母液编号且坯布重量缺失，迁移失败 → 恢复草稿
        id: "b4",
        code: "LAB-625D",
        technician: "李技术员",
        fabric: "锦纶弹力",
        weightKg: 0,
        bathRatio: 10,
        recipeId: "r1",
        recipeVersion: 1,
        finishingId: "f1",
        finishingVersion: 1,
        repairId: "rr1",
        repairVersion: 1,
        status: "待排",
        conflicts: [],
        createdAt: now - 13 * day,
      },
    ],
    curves: [
      {
        id: "c1",
        number: "TC-001",
        name: "棉府绸升温曲线",
        points: [
          { t: 0, temp: 25 },
          { t: 10, temp: 60 },
          { t: 25, temp: 95 },
          { t: 55, temp: 95 },
        ],
        synced: true,
        updatedAt: now - 1 * day,
        updatedBy: "陈技术员",
      },
    ],
    pendingCurves: [],
    conflicts: [],
    conflictDrafts: [],
    drafts: [],
  };
}
